name: __projectName__
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  intl: any

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
