name: sibem_frontend_site
description: A web app that uses AngularDart Components
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: ^3.2.1

dependencies:
  ngdart: 8.0.0-dev.4
  ngrouter: 4.0.0-dev.3
  ngforms: 5.0.0-dev.3 
  intl: any
  http: any
  js: any
  chartjs2: any  
  http_parser: any
  collection: any
  sass_builder: any

  #pdf_fork: 3.10.5
  pdf: ^3.10.8
  dart_excel:
   git:
    url: https://github.com/insinfo/dart_excel.git
    ref: main  #branch name 

  sibem_core:
    path: ../core 

dev_dependencies:  
  build_runner: ^2.1.2
  build_test: ^2.1.3
  build_web_compilers: ^4.0.0
  lints: ^2.1.0
  test: ^1.24.0
