name: darcli
description: >
  A scaffolding generator for your Dart projects. darcli helps you get set
  up!
# After changing the version, run `pub run build_runner build`.
version: 1.0.0
homepage: https://github.com/insinfo/darcli

environment: 
  sdk: ">=3.0.0 <4.0.0"

# Add the bin/darcli.dart script to the scripts pub installs.
executables:
  darcli:

dependencies:
  args: ^2.5.0 
  http: ^1.2.0
  path: ^1.9.0
 

dev_dependencies:
  build: ^2.4.1
  build_config: ^1.1.1
  build_runner: ^2.4.9
  build_version: ^2.1.1
  glob: ^2.1.2
  grinder: ^0.9.5
  source_gen: ^1.5.0
  test: ^1.25.4
  yaml: ^3.1.2
