name: sibem_backend #banco_emprego_backend

environment:  
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  #angel3_framework: ^7.0.0  
  angel3_framework: ^8.3.1
  angel3_configuration: any  
  angel3_production: any
  angel3_static: any
  belatuk_pretty_logging: any
  angel3_cors: any
  jaguar_jwt: any
  encrypt: any
  dotenv: any
  eloquent: ^3.2.1
  #eloquent:
    #path: ../../eloquent 

  #para serviço agendado em segundo plano
  cron: ^0.6.0
  #para extração de dados web
  http: any
  html: any    
  excel: ^4.0.2

  sibem_core:
    path: ../core 

dev_dependencies:
  angel3_hot: any
  angel3_test: any
  test: any
  