name: __projectName__
description: A web server built using the shelf package.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.5.0
  shelf: ^1.4.1
  path: any
  dotenv: any
  uuid: any
  jaguar_jwt: any  
  eloquent: ^3.2.1

dev_dependencies:
  lints: ^2.1.0
