name: new_sali_frontend_site
description: Web app 
# version: 1.0.0
# homepage: https://www.example.com

environment:   
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  # ngdart: 7.1.1 
  # ngforms: any #^4.1.1
  # ngrouter: any #^3.1.1   
  ngdart:     
    git:
      ref: master
      url: https://github.com/insinfo/angular_8.git
 
  
  http: any  

  new_sali_core:
    path: ../core   

  
dev_dependencies:    
  sass_builder: ^2.1.2  
  build_runner: any
  build_web_compilers: any 
  test: any
 
  puppeteer: 2.23.0
