name: __projectName__
description: A web app that uses AngularDart Components
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  ngdart: 8.0.0-dev.4
  ngrouter: 4.0.0-dev.3
  ngforms: 5.0.0-dev.3 
  collection: ^1.18.0
  http: ^1.2.0
  chartjs2: ^2.0.0
  sass_builder: ^2.2.1
  intl: ^0.18.1
  pdf: ^3.10.8
  dart_excel:
   git:
    url: https://github.com/insinfo/dart_excel.git
    ref: main  #branch name 

dev_dependencies:  
  build_runner: ^2.1.2
  build_test: ^2.1.3
  build_web_compilers: ^4.0.0
  lints: ^2.1.0
  test: ^1.24.0
