name: esic_backend
description: Backend do Sistema Eletrônico de Informações ao. Cidadão (e-SIC)

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  angel3_auth: ^7.0.0
  angel3_configuration: ^7.0.0
  angel3_framework: ^7.0.0
  angel3_jael: ^7.0.0
  angel3_production: ^7.0.0
  angel3_static: ^7.0.0
  angel3_validate: ^7.0.0
  angel3_cors: ^7.0.0
  belatuk_pretty_logging: ^5.0.0  
  uuid: ^3.0.6
  dotenv: ^4.0.1 
  mailer: ^5.2.0
  intl: ^0.17.0  
  http: ^0.13.5
  path: ^1.8.2
  jaguar_jwt: ^3.0.0
  crypto: ^3.0.2

  fluent_query_builder: ^5.5.0    
  
  esic_core:
    path: ../core


dev_dependencies:
  angel3_hot: ^7.0.1
  angel3_test: ^7.0.0
  io: ^1.0.3
  test: ^1.21.4
  lints: ^2.0.0
